name: Start Server

on:
  repository_dispatch:
    types: [start-server]

jobs:
  start-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install undetected-chromedriver selenium

      - name: Run Aternos Script
        run: |
          python main.py